#!/usr/bin/env bash
# Hermes Agent ON THE HOST (no container): one immutable release per upstream commit, built by
# upstream's own installer, run by systemd as the operator user (`hermes`, same uid as the
# workspace, sudo) with HERMES_HOME=/opt/data.
#
#   sudo ./hermes-host.sh build [<ref>]     # build a release for <ref> (default HERMES_REF, main) — nothing restarts
#   sudo ./hermes-host.sh activate <sha12>  # /opt/hermes → that release (previous kept), restart the services
#   sudo ./hermes-host.sh rollback          # back to the previous release
#   sudo ./hermes-host.sh units             # (re)write /etc/hermes/agent.env, the units, the Traefik route, ufw
#   sudo ./hermes-host.sh start|stop|restart|status|releases|probe|healthy
#   sudo ./hermes-host.sh resolve [<ref>] | current   # full sha of a ref / the active release (sha12)
#
# Layout (a native upstream install per release):
#   /opt/hermes-releases/<sha12>/app/     built by the commit's own scripts/install.sh, run as the
#                                         operator user (HOME sandboxed, HERMES_HOME=/opt/data):
#                                         .hermes/bin/hermes (launcher), tools/ (pm store: Python,
#                                         Node, uv, Chromium, ffmpeg, ripgrep), web + TUI builds, and
#                                         .hostbin/ (python3, node, npm, npx, rg, ffmpeg: stable names).
#                                         Root-owned and read-only once built.
#   /opt/hermes-releases/<sha12>/.release the full sha, written last (marks a complete release)
#   /opt/data/installs/<key>/             the release's Python environment: pm keeps it in HERMES_HOME
#                                         (key = sha256(app path)[:16]); pruned with the release
#   /opt/hermes-releases/<sha12>/ (no app/)  legacy layout (python3.13 .venv, before upstream's pm):
#                                         still runs and rolls back, no longer built
#   /opt/hermes-releases/previous         the release that ran before the last activate
#   /opt/hermes → the current release's app dir;  /opt/data → HERMES_DATA_DIR (the image's paths)
#   /etc/hermes/agent.env                 root:hermes 640 — what the compose `environment:` block was
#   /etc/hermes/image-provenance.json     makes `hermes update` refuse (this script owns updates)
#   hermes-gateway.service                generated by the active release itself at every activate (so
#                                         `hermes gateway …` sees it as current) + our drop-in
#                                         hermes-gateway.service.d/10-command-center.conf (env, limits)
#   hermes-dashboard.service              ours (hermes/hermes-dashboard.service)
#   /etc/hermes/host-guard.py             pre_tool_call hook: sudo / docker / systemctl / protected paths →
#                                         human approval (hermes/host-guard.py)
set -euo pipefail

# shellcheck disable=SC1091
. "$(dirname "$0")/lib/common.sh"
need_root
load_env

SQLITE_MIN=3.51.3   # the WAL-reset fix (pm's Python bundles a newer SQLite; checked by the smoke test)
: "${HERMES_REPO:=https://github.com/NousResearch/hermes-agent.git}" "${HERMES_REF:=main}"
: "${AGENT_MEM_LIMIT:=10g}" "${AGENT_CPUS:=6}" "${DESKTOP_PORT:=9120}"

TOOLCHAIN=/opt/hermes-toolchain   # Node of legacy releases (read-only leftovers of the old builder)
GATEWAY_DROPIN_DIR=/etc/systemd/system/hermes-gateway.service.d
DASHBOARD_UNIT=/etc/systemd/system/hermes-dashboard.service
TRAEFIK_ROUTE="$TRAEFIK_DIR/dynamic/hermes.yml"
PROVENANCE=/etc/hermes/image-provenance.json

# PATH of every Hermes process: the launcher (native) or the venv (legacy), the release's tools
# under stable names (MCP servers are `node …`), legacy Node, the agent's own ~/.local/bin.
agent_path() { echo "$HERMES_CURRENT/.hermes/bin:$HERMES_CURRENT/.hostbin:$HERMES_CURRENT/.venv/bin:$TOOLCHAIN/node/bin:/opt/data/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"; }
# release_app <sha12> — the tree Hermes runs from: <release>/app (native) or <release> (legacy).
release_app() { if [ -d "$HERMES_RELEASES/$1/app" ]; then echo "$HERMES_RELEASES/$1/app"; else echo "$HERMES_RELEASES/$1"; fi; }
current_release() {
  local p
  [ -e "$HERMES_CURRENT" ] || return 0
  p="$(readlink -f "$HERMES_CURRENT")"; [ "$(basename "$p")" != app ] || p="$(dirname "$p")"
  basename "$p"
}
release_sha() { cat "$HERMES_RELEASES/$1/.release" 2>/dev/null || true; }
# release_env_dir <app dir> — its pm environment in the data dir (pm/environments.py install_key).
release_env_dir() { echo "$HERMES_DATA_DIR/installs/$(printf '%s' "$(readlink -f "$1")" | sha256sum | cut -c1-16)"; }

# ── host packages ────────────────────────────────────────────────────────
# pm brings Python, Node, uv, Chromium, ffmpeg and ripgrep; the host brings what they link against
# (the Dockerfile's runtime_base apt layer, Ubuntu names) and the operator tools.
install_deps() {
  local missing=() p
  for p in git curl ca-certificates xz-utils procps iputils-ping openssh-client libatomic1 \
           build-essential cmake libffi-dev libolm-dev \
           libasound2t64 libatk-bridge2.0-0t64 libatk1.0-0t64 libatspi2.0-0t64 libcairo2 libcups2t64 \
           libdbus-1-3 libgbm1 libglib2.0-0t64 libnspr4 libnss3 libpango-1.0-0 libx11-6 libxcb1 \
           libxcomposite1 libxdamage1 libxext6 libxfixes3 libxkbcommon0 libxrandr2 \
           postgresql-client rsync jq tmux less; do
    dpkg-query -W -f='${Status}' "$p" 2>/dev/null | grep -q 'ok installed' || missing+=("$p")
  done
  [ "${#missing[@]}" -eq 0 ] || { info "apt install ${missing[*]}"; apt-get update -q; apt-get install -y -q --no-install-recommends "${missing[@]}"; }
}

# ── release build ────────────────────────────────────────────────────────
resolve_ref() {
  local ref="$1" sha
  if [[ "$ref" =~ ^[0-9a-f]{40}$ ]]; then echo "$ref"; return; fi
  sha="$(git ls-remote "$HERMES_REPO" "refs/heads/$ref" "refs/tags/$ref" | head -n1 | cut -f1)"
  [ -n "$sha" ] || die "cannot resolve $ref on $HERMES_REPO (a short sha? pass the full 40-char sha)"
  echo "$sha"
}

# drop_release <sha12> — the release dir and its pm environment in the data dir.
drop_release() {
  local rel="$HERMES_RELEASES/$1"
  [ ! -d "$rel/app" ] || rm -rf "$(release_env_dir "$rel/app")"
  rm -rf "${rel:?}"
}

# make_hostbin <app> — stable names for the pm tools (what the Dockerfile links into /usr/local/bin).
make_hostbin() {
  local app="$1" py
  py="$(find "$app/tools" -maxdepth 3 -path '*/python-*/bin/python3' 2>/dev/null | head -n1)"
  [ -n "$py" ] || return 1
  install -d -m 755 "$app/.hostbin"
  env -i HOME=/nonexistent HERMES_HOME="$HERMES_DATA_DIR" HERMES_RUNTIME_DIR="$app/tools" PATH=/usr/bin:/bin \
    "$py" -I -c '
import sys
from pathlib import Path
app = Path(sys.argv[1]); sys.path.insert(0, str(app))
from pm import installed_package
out = app / ".hostbin"
def link(name, target):
    target = Path(target)
    if not target.exists():
        print(f"hostbin: {name}: {target} missing", file=sys.stderr); return
    dst = out / name; dst.unlink(missing_ok=True); dst.symlink_to(target)
for cmd, pkg in (("python3", "python"), ("node", "node"), ("npm", "npm"), ("ffmpeg", "ffmpeg"), ("rg", "ripgrep")):
    try: binary = Path(installed_package(pkg).binary)
    except Exception as exc: print(f"hostbin: {pkg}: {exc}", file=sys.stderr); continue
    link(cmd, binary)
    if pkg == "npm": link("npx", binary.with_name("npx"))
    if pkg == "ffmpeg": link("ffprobe", binary.with_name("ffprobe"))
' "$app"
  [ -x "$app/.hostbin/python3" ] && [ -x "$app/.hostbin/node" ]
}

# do_build [ref] — BUILT_SHORT = the release name. Idempotent: a complete release is reused.
# The commit's own scripts/install.sh does the work (clone, pm: tools + locked Python environment,
# TUI/web builds, command), as the operator user: its environment lands in /opt/data/installs,
# which the agent reads at run time. HOME is a throwaway dir (the installer edits shell rc files
# and publishes ~/.local/bin/hermes); only then is the tree sealed root-owned.
do_build() {
  local sha short rel app sandbox rc=0
  install_deps
  sha="$(resolve_ref "${1:-$HERMES_REF}")"; short="${sha:0:12}"; rel="$HERMES_RELEASES/$short"; app="$rel/app"
  BUILT_SHORT="$short"
  if [ "$(release_sha "$short")" = "$sha" ]; then info "release $short already built"; return 0; fi
  install -d -m 755 "$HERMES_RELEASES"
  drop_release "$short"; rm -rf "${rel:?}.failed"   # a leftover without .release = interrupted build
  install -d -m 755 -o "$OP_USER" -g "$HERMES_GID" "$rel"
  sandbox="$(mktemp -d /var/tmp/hermes-build.XXXXXX)"
  install -d -m 700 -o "$OP_USER" -g "$HERMES_GID" "$sandbox/home" "$sandbox/src"
  chown "$OP_USER:$HERMES_GID" "$sandbox"
  info "Fetching the installer of $short…"
  runuser -u "$OP_USER" -- sh -c 'cd "$1" && git init -q && git fetch -q --depth 1 "$2" "$3" && git show FETCH_HEAD:scripts/install.sh > ../install.sh' \
    sh "$sandbox/src" "$HERMES_REPO" "$sha" 2>&1 || { rm -rf "$sandbox"; drop_release "$short"; die "cannot fetch scripts/install.sh at $short"; }
  # The installer's post-build maintenance migrates the live config.yaml: keep the one the running
  # release knows, to put back if this release is rolled back.
  install -d -m 700 -o "$OP_USER" -g "$HERMES_GID" "$HERMES_DATA_DIR/backups"
  install -m 600 -o "$OP_USER" -g "$HERMES_GID" "$HERMES_DATA_DIR/config.yaml" "$HERMES_DATA_DIR/backups/config.yaml.before-$short"
  info "Building Hermes $short with its own installer (as $OP_USER, HERMES_HOME=/opt/data)…"
  runuser -u "$OP_USER" -- env -i HOME="$sandbox/home" HERMES_HOME=/opt/data HERMES_RUNTIME_DIR="$app/tools" \
    HERMES_REPO_URL="$HERMES_REPO" PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    LANG=C.UTF-8 SHELL=/bin/bash \
    bash "$sandbox/install.sh" --commit "$sha" --dir "$app" --hermes-home /opt/data --non-interactive --verbose || rc=$?
  rm -rf "$sandbox"
  if [ "$rc" -ne 0 ] || [ ! -x "$app/.hermes/bin/hermes" ]; then
    drop_release "$short"; die "upstream installer failed for $short (exit $rc)"
  fi
  make_hostbin "$app" || { drop_release "$short"; die "cannot link the pm tools of $short (.hostbin)"; }
  echo "$sha" > "$app/.hermes_build_sha"
  chown -R root:root "$rel"; chmod -R a+rX,go-w "$rel"
  if ! smoke_test "$app"; then
    rm -rf "${rel:?}.failed"; mv "$rel" "$rel.failed"   # kept for a look (its environment stays until the next build of $short)
    die "release $short fails its smoke test — kept as $rel.failed"
  fi
  echo "$sha" > "$rel/.release"   # written last: marks a complete release
  info "release $short built"
}

# smoke_test <app> — as the runtime user, on the real data dir, read-only commands: the CLI starts
# (config and dependencies load), SQLite has the WAL-reset fix, Node runs, web + TUI are built.
smoke_test() {
  local app="$1" hermes py node home rc=0
  if [ -x "$app/.hermes/bin/hermes" ]; then hermes="$app/.hermes/bin/hermes"; py="$app/.hostbin/python3"; node="$app/.hostbin/node"
  else hermes="$app/.venv/bin/hermes"; py="$app/.venv/bin/python"; node="$TOOLCHAIN/node/bin/node"; fi
  home="$(mktemp -d)"; chown "$OP_USER" "$home"
  runuser -u "$OP_USER" -- env -i HOME="$home" HERMES_HOME=/opt/data HERMES_RUNTIME_DIR="$app/tools" \
    PATH=/usr/bin:/bin PYTHONDONTWRITEBYTECODE=1 sh -c '
    set -e
    "$1" --version
    "$1" config get model >/dev/null
    "$2" - "$4" <<"PY"
import sqlite3, sys
v = sqlite3.sqlite_version_info
assert v >= tuple(int(x) for x in sys.argv[1].split(".")), "SQLite %s has the WAL-reset bug" % sqlite3.sqlite_version
db = sqlite3.connect(":memory:")
db.execute("CREATE VIRTUAL TABLE docs USING fts5(content, tokenize='"'"'trigram'"'"')")
db.execute("INSERT INTO docs VALUES ('"'"'hermes'"'"')")
assert db.execute("SELECT count(*) FROM docs WHERE docs MATCH '"'"'erm'"'"'").fetchone()[0] == 1, "FTS5 trigram"
print("sqlite", sqlite3.sqlite_version)
PY
    "$3" --version
    test -f "$5/hermes_cli/web_dist/index.html"
    test -f "$5/ui-tui/dist/entry.js"
  ' sh "$hermes" "$py" "$node" "$SQLITE_MIN" "$app" || rc=$?
  rm -rf "$home"
  return "$rc"
}

# ── units, env, route ────────────────────────────────────────────────────
# /etc/hermes/agent.env — the compose `environment:` block + the image ENV. Read by both units,
# agent_run/agent_exec and bin/hermes (group hermes: the agent already had all of it in its env).
# Legacy releases (python3.13 .venv) kept Playwright's browsers in the tree; pm finds its Chromium itself.
legacy_env() { [ ! -x "$HERMES_CURRENT/.venv/bin/hermes" ] || printf 'VIRTUAL_ENV=%s\nPLAYWRIGHT_BROWSERS_PATH=%s\n' "$HERMES_CURRENT/.venv" "$HERMES_CURRENT/.playwright"; }

write_agent_env() {
  install -d -m 755 /etc/hermes
  local tmp; tmp="$(mktemp /etc/hermes/.agent.env.XXXXXX)"
  cat > "$tmp" <<EOF
# Generated by hermes-host.sh units from $STACK_DIR/.env — edit .env, then: sudo command-center hermes units
HOME=/opt/data
HERMES_HOME=/opt/data
PATH=$(agent_path)
HERMES_RUNTIME_DIR=$HERMES_CURRENT/tools
TZ=${TZ:-UTC}
LANG=C.UTF-8
PYTHONUNBUFFERED=1
PYTHONDONTWRITEBYTECODE=1
$(legacy_env)HERMES_WEB_DIST=$HERMES_CURRENT/hermes_cli/web_dist
HERMES_TUI_DIR=$HERMES_CURRENT/ui-tui
HERMES_DISABLE_LAZY_INSTALLS=1
HERMES_LAZY_INSTALL_TARGET=/opt/data/lazy-packages
DISABLE_AUTOUPDATER=1
CODEX_DISABLE_UPDATE_CHECK=1
# Bound to one IP, the dashboard only accepts that Host or its public URL (Traefik sends HERMES_HOST).
HERMES_DASHBOARD_PUBLIC_URL=https://$HERMES_HOST
HERMES_DASHBOARD_BASIC_AUTH_USERNAME=${DESKTOP_USERNAME:-admin}
HERMES_DASHBOARD_BASIC_AUTH_PASSWORD=${DESKTOP_PASSWORD:?set by install.sh}
HERMES_DASHBOARD_BASIC_AUTH_SECRET=${DESKTOP_SECRET:?set by install.sh}
GH_CONFIG_DIR=/opt/data/home/.config/gh
GIT_CONFIG_GLOBAL=/opt/data/home/.gitconfig
API_SERVER_ENABLED=true
API_SERVER_HOST=127.0.0.1
API_SERVER_PORT=8642
API_SERVER_KEY=${API_SERVER_KEY:?set by install.sh}
PGHOST=127.0.0.1
PGPORT=${POSTGRES_PORT:-5432}
PGUSER=$POSTGRES_USER
PGPASSWORD=${POSTGRES_PASSWORD:?set by install.sh}
PGDATABASE=$POSTGRES_DB
DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@127.0.0.1:${POSTGRES_PORT:-5432}/$POSTGRES_DB
OBSIDIAN_VAULT_PATH=$HERMES_WORKSPACE_DIR/$OBSIDIAN_VAULT_DIR
WORKSPACE_DIR=$HERMES_WORKSPACE_DIR
EOF
  chown "root:$HERMES_GID" "$tmp"; chmod 640 "$tmp"; mv -f "$tmp" "$AGENT_ENV"
}

write_provenance() {
  local sha="$1" version
  install -d -m 755 /etc/hermes
  version="$(sed -n 's/^version = "\(.*\)"/\1/p' "$(release_app "${sha:0:12}")/pyproject.toml" | head -n1)"
  printf '{"deployment_kind":"image","image":"host:%s","manager":"command-center","revision":"%s","schema":1,"version":"%s"}\n' \
    "$HERMES_RELEASES" "$sha" "${version:-unknown}" > "$PROVENANCE.tmp"
  chmod 444 "$PROVENANCE.tmp"; mv -f "$PROVENANCE.tmp" "$PROVENANCE"
}

# hermes-gateway.service = what the active release generates for a system unit (so `hermes gateway …`
# sees it as current; its ExecStart runs that release), our settings in a drop-in (EnvironmentFile
# wins over its Environment=). Regenerated at every activate / rollback.
write_units() {
  local mem="${AGENT_MEM_LIMIT^^}" hermes_bin
  [ -n "$(release_sha "$(current_release)")" ] || die "no active release: sudo $0 build && sudo $0 activate <sha12>"
  hermes_py '
import sys
try: from hermes_cli.gateway_service_unit import generate_systemd_unit
except ImportError: from hermes_cli.gateway import generate_systemd_unit
sys.stdout.write(generate_systemd_unit(system=True, run_as_user=sys.argv[1]))' "$OP_USER" 2>/dev/null > /etc/systemd/system/.hermes-gateway.service.tmp
  grep -q '^ExecStart=' /etc/systemd/system/.hermes-gateway.service.tmp || die "generated gateway unit is empty"
  mv -f /etc/systemd/system/.hermes-gateway.service.tmp /etc/systemd/system/hermes-gateway.service
  install -d "$GATEWAY_DROPIN_DIR"
  sed -e "s|@ENV@|$AGENT_ENV|g" -e "s|@MEM@|$mem|g" -e "s|@CPUS@|$((AGENT_CPUS * 100))%|g" \
    "$STACK_DIR/hermes/gateway-dropin.conf" > "$GATEWAY_DROPIN_DIR/10-command-center.conf"
  hermes_bin="$HERMES_CURRENT/.hermes/bin/hermes"; [ -x "$hermes_bin" ] || hermes_bin="$HERMES_CURRENT/.venv/bin/hermes"
  sed -e "s|@USER@|$OP_USER|g" -e "s|@HERMES@|$hermes_bin|g" -e "s|@ENV@|$AGENT_ENV|g" \
    -e "s|@BIND@|${DESKTOP_BIND:-127.0.0.1}|g" -e "s|@PORT@|$DESKTOP_PORT|g" \
    "$STACK_DIR/hermes/hermes-dashboard.service" > "$DASHBOARD_UNIT"
  alias_gateway_unit
  systemctl daemon-reload
  systemctl enable hermes-gateway.service hermes-dashboard.service >/dev/null 2>&1
}

# Hermes names the unit of a HERMES_HOME outside ~/.hermes `hermes-gateway-<hash>`; only root sees
# the bare hermes-gateway.service as ours. Without this alias the agent (not root) would think its
# gateway runs "manually", and `hermes gateway restart` would not go through systemd.
alias_gateway_unit() {
  local name
  name="$(hermes_py 'from hermes_cli.gateway import get_service_name; print(get_service_name())' 2>/dev/null | tail -n1)"
  case "$name" in
    hermes-gateway) ;;
    hermes-gateway-*) [[ "$name" =~ ^hermes-gateway-[a-z0-9_-]+$ ]] || die "unexpected gateway unit name: $name"
                      ln -sfn hermes-gateway.service "/etc/systemd/system/$name.service" ;;
    *) warn "cannot read the gateway unit name Hermes expects (got: ${name:-nothing}) — no alias" ;;
  esac
}

# Traefik (container) → dashboard (host). File provider: the docker provider only sees containers.
write_route() {
  install -d -m 755 "$(dirname "$TRAEFIK_ROUTE")"
  cat > "$TRAEFIK_ROUTE.tmp" <<EOF
# Generated by hermes-host.sh units — https://$HERMES_HOST → the dashboard on the host.
http:
  routers:
    hermes:
      rule: Host(\`$HERMES_HOST\`)
      entryPoints: [websecure]
      tls:
        certResolver: cloudflare
      service: hermes
  services:
    hermes:
      loadBalancer:
        servers:
          - url: "http://${DESKTOP_BIND:-127.0.0.1}:$DESKTOP_PORT"
EOF
  chmod 644 "$TRAEFIK_ROUTE.tmp"; mv -f "$TRAEFIK_ROUTE.tmp" "$TRAEFIK_ROUTE"
}

# Traefik's packets come from the proxy bridge, not tailscale0: ufw must let them reach the
# dashboard port (harden.sh re-adds the same rule after its ufw reset).
allow_proxy_to_dashboard() {
  command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q '^Status: active' || return 0
  ufw allow proto tcp from "${PROXY_SUBNET:-172.20.0.0/16}" to any port "$DESKTOP_PORT" comment 'traefik → hermes dashboard (host)' >/dev/null
}

# The host-action approval gate (hermes/host-guard.py, option B): root-owned copy, consent for the
# gateway (non-TTY: exact command in Hermes' hook allowlist), and the hooks.pre_tool_call entry.
GUARD=/etc/hermes/host-guard.py
install_guard() {
  local hooks
  install -d -m 755 /etc/hermes
  install -m 755 -o root -g root "$STACK_DIR/hermes/host-guard.py" "$GUARD.tmp"
  "$GUARD.tmp" --self-test >/dev/null || { rm -f "$GUARD.tmp"; die "host-guard.py fails its self-test"; }
  mv -f "$GUARD.tmp" "$GUARD"
  runuser -u "$OP_USER" -- python3 -c '
import json, os, sys
path, cmd = sys.argv[1], sys.argv[2]
try:
    with open(path, encoding="utf-8") as f: data = json.load(f)
except FileNotFoundError: data = {}
approvals = data.setdefault("approvals", [])
if not any(a.get("event") == "pre_tool_call" and a.get("command") == cmd for a in approvals):
    approvals.append({"event": "pre_tool_call", "command": cmd})
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f: json.dump(data, f, indent=2); f.write("\n")
    os.chmod(tmp, 0o600); os.replace(tmp, path)
' "$HERMES_DATA_DIR/shell-hooks-allowlist.json" "$GUARD"
  hooks="$(hermes_py '
import json, sys, yaml
cmd = sys.argv[1]
with open("/opt/data/config.yaml", encoding="utf-8") as f: cfg = yaml.safe_load(f) or {}
entries = list(((cfg.get("hooks") or {}).get("pre_tool_call")) or [])
if not any(isinstance(e, dict) and e.get("command") == cmd for e in entries):
    entries.append({"matcher": "terminal|execute_code|write_file|patch", "command": cmd, "timeout": 10, "fail_closed": True})
    print(json.dumps(entries))
' "$GUARD")" || die "cannot read /opt/data/config.yaml"
  [ -z "$hooks" ] || agent_run hermes config set hooks.pre_tool_call "$hooks" >/dev/null
}

do_units() {
  no_symlink "$HERMES_DATA_DIR"
  if [ -L /opt/data ] || [ ! -e /opt/data ]; then ln -sfn "$HERMES_DATA_DIR" /opt/data
  else die "/opt/data exists and is not a symlink — expected a link to $HERMES_DATA_DIR"; fi
  write_agent_env
  write_units
  write_route
  allow_proxy_to_dashboard
  install_guard
  info "units, $AGENT_ENV, Traefik route, ufw rule and host-action guard written"
}

# ── activate / services ──────────────────────────────────────────────────
# activate <short> — current → <short>, previous → the old current; other complete releases pruned.
activate() {
  local short="$1" cur d
  [ -n "$(release_sha "$short")" ] || die "no complete release $short in $HERMES_RELEASES"
  cur="$(current_release)"
  if [ "$cur" != "$short" ]; then
    [ -z "$cur" ] || ln -sfn "$HERMES_RELEASES/$cur" "$HERMES_RELEASES/previous"
    ln -sfn "$(release_app "$short")" "$HERMES_CURRENT.tmp" && mv -Tf "$HERMES_CURRENT.tmp" "$HERMES_CURRENT"
  fi
  ln -sfn "$STACK_DIR/bin/hermes" /usr/local/bin/hermes
  write_provenance "$(release_sha "$short")"
  for d in "$HERMES_RELEASES"/*/; do
    d="$(basename "$d")"
    case "$d" in "$short"|"$cur"|previous) ;; *) [ ! -e "$HERMES_RELEASES/$d/.release" ] || drop_release "$d" ;; esac
  done
  info "Hermes release: ${cur:-none} → $short"
}

services_restart() {
  systemctl restart hermes-gateway.service hermes-dashboard.service
  agent_wait_healthy 180
}

do_rollback() {
  local prev
  prev=""; [ ! -e "$HERMES_RELEASES/previous" ] || prev="$(basename "$(readlink -f "$HERMES_RELEASES/previous")")"
  [ -n "$prev" ] && [ -n "$(release_sha "$prev")" ] || die "no previous release kept"
  activate "$prev"
  do_units
  services_restart || warn "hermes not healthy after the rollback: journalctl -u hermes-gateway -u hermes-dashboard"
}

do_status() {
  local cur prev
  cur="$(current_release)"; prev=""
  [ ! -e "$HERMES_RELEASES/previous" ] || prev="$(basename "$(readlink -f "$HERMES_RELEASES/previous")")"
  printf '  %-10s %s\n' release "${cur:-none}  $(release_sha "$cur")" previous "${prev:-none}"
  printf '  %-10s %s\n' gateway "$(systemctl is-active hermes-gateway 2>/dev/null || true)" dashboard "$(systemctl is-active hermes-dashboard 2>/dev/null || true)"
  if agent_healthy; then printf '  %-10s %s\n' health "ok (gateway /health + dashboard /api/status)"
  else printf '  %-10s %s\n' health "NOT OK"; fi
}

# A build (uv, npm, vite) takes GBs of RAM: run it in its own transient unit, never in the caller's
# cgroup — from a herdr pane (herdr.service MemoryMax) the OOM killer would take the terminal too.
build_in_own_unit() {
  [ "${HERMES_BUILD_UNIT:-}" = 1 ] && return 0
  command -v systemd-run >/dev/null 2>&1 || return 0
  exec systemd-run --quiet --pipe --wait --collect --unit="hermes-build-$$" \
    -p MemoryMax="${HERMES_BUILD_MEM:-8G}" -p MemorySwapMax=0 -E HERMES_BUILD_UNIT=1 \
    "$(readlink -f "$0")" build "$@"
}

cmd="${1:-}"; [ $# -gt 0 ] && shift
case "$cmd" in
  build)    build_in_own_unit "$@"; do_build "${1:-}"; echo "$BUILT_SHORT" ;;
  # A new release may ship a new unit template: regenerate it before the restart.
  activate) [ -n "${1:-}" ] || die "usage: $0 activate <sha12>"; activate "$1"; do_units; services_restart ;;
  resolve)  resolve_ref "${1:-$HERMES_REF}" ;;
  current)  current_release ;;
  rollback) do_rollback ;;
  units)    do_units ;;
  start)    systemctl start hermes-gateway.service hermes-dashboard.service; agent_wait_healthy 180 ;;
  stop)     systemctl stop hermes-dashboard.service hermes-gateway.service ;;
  restart)  services_restart ;;
  status)   do_status ;;
  releases) ls -1 "$HERMES_RELEASES" 2>/dev/null || true; echo "current: $(current_release)" ;;
  probe)    smoke_test "$(release_app "$(current_release)")" ;;
  healthy)  agent_healthy ;;
  -h|--help|help|"") sed -n '2,12p' "$0" ;;
  *) die "usage: $0 {build [ref]|activate <sha12>|rollback|units|start|stop|restart|status|releases|probe|healthy|resolve [ref]|current}" ;;
esac
