#!/usr/bin/env bash
# Hermes Agent ON THE HOST (no container): one immutable release per upstream commit, run by
# systemd as the operator user (`hermes`, same uid as the workspace, sudo) with HERMES_HOME=/opt/data.
#
#   sudo ./hermes-host.sh build [<ref>]     # build a release for <ref> (default HERMES_REF, main) — nothing restarts
#   sudo ./hermes-host.sh activate <sha12>  # /opt/hermes → that release (previous kept), restart the services
#   sudo ./hermes-host.sh rollback          # back to the previous release
#   sudo ./hermes-host.sh units             # (re)write /etc/hermes/agent.env, the units, the Traefik route, ufw
#   sudo ./hermes-host.sh start|stop|restart|status|releases|probe|healthy
#   sudo ./hermes-host.sh resolve [<ref>] | current   # full sha of a ref / the active release (sha12)
#
# Layout:
#   /opt/hermes-releases/<sha12>/   checkout + .venv + node_modules + web build (root, read-only);
#                                   .release = the full sha, written last (marks a complete tree)
#   /opt/hermes-releases/previous   symlink to the release that ran before the last activate
#   /opt/hermes → the current release (the path the image used: /opt/hermes/.venv/bin/hermes)
#   /opt/hermes-toolchain/          pinned uv, Node, fixed SQLite (shared by the releases)
#   /opt/data → HERMES_DATA_DIR     the data dir at the image's path: config.yaml, MCP commands and
#                                   .env keep their /opt/data/... paths
#   /etc/hermes/agent.env           root:hermes 640 — what the compose `environment:` block was
#   /etc/hermes/image-provenance.json   makes `hermes update` refuse (this script owns updates)
#   hermes-gateway.service          generated by Hermes itself (it repairs it when outdated), + our
#                                   drop-in hermes-gateway.service.d/10-command-center.conf
#   hermes-dashboard.service        ours (hermes/hermes-dashboard.service)
#   /etc/hermes/host-guard.py       pre_tool_call hook: sudo / docker / systemctl / protected paths →
#                                   human approval (hermes/host-guard.py)
#
# Python is Ubuntu's deadsnakes python3.13 (same ABI as the image: data/lazy-packages stays valid)
# with the WAL-reset-fixed SQLite preloaded by a .pth in the venv (the image replaced libsqlite3).
set -euo pipefail

# shellcheck disable=SC1091
. "$(dirname "$0")/lib/common.sh"
need_root
load_env

UV_VERSION=0.11.6
UV_SHA256=0c6bab77a67a445dc849ed5e8ee8d3cb333b6e2eba863643ce1e228075f27943
NODE_VERSION=v26.5.1
SQLITE_AUTOCONF_VERSION=3530400
SQLITE_SHA256=0e9483900e92cd5de8fd48d16bf9200145a61f7fd5be542a5ac81d8a9516eb9c
SQLITE_MIN=3.51.3
# Extras = those of the release's own Dockerfile (`RUN uv sync … --extra X`), so every release
# gets what the published image of the same commit bakes; this list only when none can be read.
UV_EXTRAS_FALLBACK=(all messaging otlp anthropic bedrock azure-identity matrix google-chat)
PYTHON_BIN=/usr/bin/python3.13
: "${HERMES_REPO:=https://github.com/NousResearch/hermes-agent.git}" "${HERMES_REF:=main}"
: "${AGENT_MEM_LIMIT:=10g}" "${AGENT_CPUS:=6}" "${DESKTOP_PORT:=9120}"

TOOLCHAIN=/opt/hermes-toolchain
SQLITE_LIB="$TOOLCHAIN/sqlite/lib/libsqlite3.so.0"
GATEWAY_DROPIN_DIR=/etc/systemd/system/hermes-gateway.service.d
DASHBOARD_UNIT=/etc/systemd/system/hermes-dashboard.service
TRAEFIK_ROUTE="$TRAEFIK_DIR/dynamic/hermes.yml"
PROVENANCE=/etc/hermes/image-provenance.json

# PATH of every Hermes process: the active release's venv, then the pinned Node (MCP servers are `node …`).
agent_path() { echo "$HERMES_CURRENT/.venv/bin:$TOOLCHAIN/node/bin:/opt/data/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"; }
current_release() { [ -e "$HERMES_CURRENT" ] && basename "$(readlink -f "$HERMES_CURRENT")" || true; }
release_sha() { cat "$HERMES_RELEASES/$1/.release" 2>/dev/null || true; }

# ── toolchain ────────────────────────────────────────────────────────────
install_deps() {
  local missing=() p
  if [ ! -x "$PYTHON_BIN" ]; then
    info "Adding the deadsnakes PPA (python3.13, same ABI as the image)…"
    apt-get update -q && apt-get install -y -q --no-install-recommends software-properties-common
    add-apt-repository -y ppa:deadsnakes/ppa
  fi
  # Build + runtime deps of the image (Dockerfile apt layer) + the operator tools it added.
  for p in python3.13 python3.13-dev python3.13-venv build-essential cmake libffi-dev libolm-dev \
           ripgrep ffmpeg git curl xz-utils procps iputils-ping libatomic1 openssh-client \
           postgresql-client rsync jq tmux less; do
    dpkg-query -W -f='${Status}' "$p" 2>/dev/null | grep -q 'ok installed' || missing+=("$p")
  done
  [ "${#missing[@]}" -eq 0 ] || { info "apt install ${missing[*]}"; apt-get update -q; apt-get install -y -q --no-install-recommends "${missing[@]}"; }
}

install_uv() {
  local dir="$TOOLCHAIN/uv-$UV_VERSION" tmp
  if [ ! -x "$dir/uv" ]; then
    info "uv $UV_VERSION"
    tmp="$(mktemp -d)"
    curl -fsSL -o "$tmp/uv.tgz" "https://github.com/astral-sh/uv/releases/download/$UV_VERSION/uv-x86_64-unknown-linux-gnu.tar.gz"
    echo "$UV_SHA256  $tmp/uv.tgz" | sha256sum -c --quiet || die "uv: sha256 mismatch"
    tar -xzf "$tmp/uv.tgz" -C "$tmp"
    install -d "$dir"; install -m 755 "$tmp/uv-x86_64-unknown-linux-gnu/uv" "$tmp/uv-x86_64-unknown-linux-gnu/uvx" "$dir/"
    rm -rf "$tmp"
  fi
  ln -sfn "uv-$UV_VERSION" "$TOOLCHAIN/uv"
}

install_node() {
  local dir="$TOOLCHAIN/node-$NODE_VERSION" tmp f
  if [ ! -x "$dir/bin/node" ]; then
    info "Node $NODE_VERSION (Hermes pins Node 26; the host's /usr/bin/node is left alone)"
    tmp="$(mktemp -d)"; f="node-$NODE_VERSION-linux-x64.tar.xz"
    curl -fsSL -o "$tmp/$f" "https://nodejs.org/dist/$NODE_VERSION/$f"
    curl -fsSL "https://nodejs.org/dist/$NODE_VERSION/SHASUMS256.txt" | grep " $f\$" > "$tmp/sum"
    (cd "$tmp" && sha256sum -c --quiet sum) || die "node: sha256 mismatch"
    install -d "$dir"; tar -xJf "$tmp/$f" -C "$dir" --strip-components=1 --no-same-owner
    rm -rf "$tmp"
  fi
  ln -sfn "node-$NODE_VERSION" "$TOOLCHAIN/node"
}

# The fixed SQLite of the image (Dockerfile sqlite_build stage: same version, checksum and flags).
install_sqlite() {
  local dir="$TOOLCHAIN/sqlite-$SQLITE_AUTOCONF_VERSION" tmp src
  if [ ! -e "$dir/lib/libsqlite3.so.0" ]; then
    info "SQLite $SQLITE_AUTOCONF_VERSION (WAL-reset fix) — build"
    tmp="$(mktemp -d)"
    curl -fsSL -o "$tmp/sqlite.tar.gz" "https://sqlite.org/2026/sqlite-autoconf-$SQLITE_AUTOCONF_VERSION.tar.gz" \
      || curl -fsSL -o "$tmp/sqlite.tar.gz" "https://sources.buildroot.net/sqlite/sqlite-autoconf-$SQLITE_AUTOCONF_VERSION.tar.gz"
    echo "$SQLITE_SHA256  $tmp/sqlite.tar.gz" | sha256sum -c --quiet || die "sqlite: sha256 mismatch"
    tar -xzf "$tmp/sqlite.tar.gz" -C "$tmp"; src="$tmp/sqlite-autoconf-$SQLITE_AUTOCONF_VERSION"
    (cd "$src" && CFLAGS="-O2 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 \
        -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_GEOPOLY -DSQLITE_ENABLE_COLUMN_METADATA \
        -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_ENABLE_DBSTAT_VTAB -DSQLITE_ENABLE_DBPAGE_VTAB \
        -DSQLITE_ENABLE_MATH_FUNCTIONS -DSQLITE_ENABLE_PREUPDATE_HOOK -DSQLITE_ENABLE_SESSION \
        -DSQLITE_SECURE_DELETE -DSQLITE_THREADSAFE=1 -DSQLITE_MAX_VARIABLE_NUMBER=250000" \
        ./configure --prefix="$dir" --disable-static >/dev/null && make -j"$(nproc)" >/dev/null && make install >/dev/null) \
      || die "sqlite build failed"
    rm -rf "$tmp"
  fi
  ln -sfn "sqlite-$SQLITE_AUTOCONF_VERSION" "$TOOLCHAIN/sqlite"
}

ensure_toolchain() {
  install -d -m 755 "$TOOLCHAIN"
  install_deps; install_uv; install_node; install_sqlite
}

# ── release build ────────────────────────────────────────────────────────
resolve_ref() {
  local ref="$1" sha
  if [[ "$ref" =~ ^[0-9a-f]{40}$ ]]; then echo "$ref"; return; fi
  sha="$(git ls-remote "$HERMES_REPO" "refs/heads/$ref" "refs/tags/$ref" | head -n1 | cut -f1)"
  [ -n "$sha" ] || die "cannot resolve $ref on $HERMES_REPO (a short sha? pass the full 40-char sha)"
  echo "$sha"
}

# build_env <release dir> <cmd…> — root, toolchain first on PATH, caches outside the release.
# No UV_PYTHON here: `uv pip` would then target that interpreter (the system one), not the venv.
build_env() {
  local dir="$1"; shift
  env -i HOME=/root PATH="$TOOLCHAIN/uv:$TOOLCHAIN/node/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
    LANG=C.UTF-8 UV_PYTHON_DOWNLOADS=never UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy \
    UV_CACHE_DIR=/var/cache/hermes-build/uv npm_config_cache=/var/cache/hermes-build/npm npm_config_install_links=false \
    PLAYWRIGHT_BROWSERS_PATH="$dir/.playwright" "$@"
}

# do_build [ref] — BUILT_SHORT = the release dir name. Idempotent: a complete release is reused.
do_build() {
  local sha short dir extras=() e site
  ensure_toolchain
  sha="$(resolve_ref "${1:-$HERMES_REF}")"; short="${sha:0:12}"; dir="$HERMES_RELEASES/$short"
  BUILT_SHORT="$short"
  if [ "$(release_sha "$short")" = "$sha" ]; then info "release $short already built"; return 0; fi
  install -d -m 755 "$HERMES_RELEASES" /var/cache/hermes-build
  rm -rf "${dir:?}" "$dir.failed"   # a leftover without .release = interrupted build
  info "Building Hermes $short in $dir (venv at its final path: its shebangs pin this release)…"
  git init -q "$dir"
  git -C "$dir" fetch -q --depth 1 "$HERMES_REPO" "$sha"
  git -C "$dir" -c advice.detachedHead=false checkout -q FETCH_HEAD
  rm -rf "$dir/.git"
  mapfile -t extras < <(grep -m1 -E '^RUN uv sync ' "$dir/Dockerfile" 2>/dev/null | grep -oE -- '--extra [A-Za-z0-9_-]+' | tr ' ' '\n')
  if [ "${#extras[@]}" -eq 0 ]; then
    warn "no \`uv sync --extra\` in the release's Dockerfile — using ${UV_EXTRAS_FALLBACK[*]}"
    for e in "${UV_EXTRAS_FALLBACK[@]}"; do extras+=(--extra "$e"); done
  fi
  info "uv sync ${extras[*]}"
  (cd "$dir" && build_env "$dir" uv venv -q --python "$PYTHON_BIN" .venv \
    && build_env "$dir" uv sync -q --frozen --no-install-project --python .venv/bin/python "${extras[@]}") \
    || { rm -rf "$dir"; die "uv sync failed"; }
  (cd "$dir" && build_env "$dir" npm install --prefer-offline --no-audit --no-fund --fetch-retries=5 --loglevel=error \
    && build_env "$dir" npx playwright install --with-deps chromium --only-shell \
    && cd web && build_env "$dir" npm run build --silent && cd ../ui-tui && build_env "$dir" npm run build --silent) \
    || { rm -rf "$dir"; die "npm install / web build failed"; }
  (cd "$dir" && build_env "$dir" uv pip install -q --python .venv/bin/python --no-deps -e .) || { rm -rf "$dir"; die "editable install failed"; }
  [ -x "$dir/.venv/bin/hermes" ] || { rm -rf "$dir"; die "editable install did not create .venv/bin/hermes"; }
  # The image swapped libsqlite3 for a fixed build; here the fixed one is preloaded (same SONAME)
  # before _sqlite3 is dlopen'ed — for every python of this venv, and only for it.
  site="$dir/.venv/lib/python3.13/site-packages"
  [ -d "$site" ] || { rm -rf "$dir"; die "unexpected venv layout: $site missing"; }
  printf 'import ctypes; ctypes.CDLL("%s", mode=ctypes.RTLD_GLOBAL)\n' "$SQLITE_LIB" > "$site/00-hermes-sqlite.pth"
  echo "$sha" > "$dir/.hermes_build_sha"
  chown -R root:root "$dir"; chmod -R a+rX,go-w "$dir"
  if ! smoke_test "$dir"; then
    rm -rf "${dir:?}.failed"; mv "$dir" "$dir.failed"   # kept for a look; the next build of $short replaces it
    die "release $short fails its smoke test — kept as $dir.failed"
  fi
  echo "$sha" > "$dir/.release"   # written last: marks a complete release
  info "release $short built"
}

# smoke_test <dir> — as the runtime user, throwaway HERMES_HOME: CLI, SQLite, Node, web assets.
smoke_test() {
  local dir="$1" home rc=0
  home="$(mktemp -d)"; chown "$OP_USER" "$home"
  runuser -u "$OP_USER" -- env -i HOME="$home" PATH="$TOOLCHAIN/node/bin:/usr/bin:/bin" HERMES_HOME="$home" \
    PYTHONDONTWRITEBYTECODE=1 sh -c '
    set -e
    "$1/.venv/bin/hermes" --version
    "$1/.venv/bin/python" - "$2" <<"PY"
import sqlite3, sys
v = sqlite3.sqlite_version_info
assert v >= tuple(int(x) for x in sys.argv[1].split(".")), "linked SQLite %s has the WAL-reset bug" % sqlite3.sqlite_version
db = sqlite3.connect(":memory:")
db.execute("CREATE VIRTUAL TABLE docs USING fts5(content, tokenize='"'"'trigram'"'"')")
db.execute("INSERT INTO docs VALUES ('"'"'hermes'"'"')")
assert db.execute("SELECT count(*) FROM docs WHERE docs MATCH '"'"'erm'"'"'").fetchone()[0] == 1, "FTS5 trigram"
import gateway.run, hermes_cli.main_dashboard  # noqa: F401 — both services import
print("sqlite", sqlite3.sqlite_version)
PY
    node --version
    test -f "$1/hermes_cli/web_dist/index.html"
    test -f "$1/ui-tui/dist/entry.js"
  ' sh "$dir" "$SQLITE_MIN" || rc=$?
  rm -rf "$home"
  return "$rc"
}

# ── units, env, route ────────────────────────────────────────────────────
# /etc/hermes/agent.env — the compose `environment:` block + the image ENV. Read by both units,
# agent_run/agent_exec and bin/hermes (group hermes: the agent already had all of it in its env).
write_agent_env() {
  install -d -m 755 /etc/hermes
  local tmp; tmp="$(mktemp /etc/hermes/.agent.env.XXXXXX)"
  cat > "$tmp" <<EOF
# Generated by hermes-host.sh units from $STACK_DIR/.env — edit .env, then: sudo command-center hermes units
HOME=/opt/data
HERMES_HOME=/opt/data
PATH=$(agent_path)
VIRTUAL_ENV=$HERMES_CURRENT/.venv
TZ=${TZ:-UTC}
LANG=C.UTF-8
PYTHONUNBUFFERED=1
PYTHONDONTWRITEBYTECODE=1
PLAYWRIGHT_BROWSERS_PATH=$HERMES_CURRENT/.playwright
HERMES_WEB_DIST=$HERMES_CURRENT/hermes_cli/web_dist
HERMES_TUI_DIR=$HERMES_CURRENT/ui-tui
HERMES_DISABLE_LAZY_INSTALLS=1
HERMES_LAZY_INSTALL_TARGET=/opt/data/lazy-packages
DISABLE_AUTOUPDATER=1
CODEX_DISABLE_UPDATE_CHECK=1
HERMES_DASHBOARD_BASIC_AUTH_USERNAME=${DESKTOP_USERNAME:-admin}
HERMES_DASHBOARD_BASIC_AUTH_PASSWORD=${DESKTOP_PASSWORD:?set by install.sh}
HERMES_DASHBOARD_BASIC_AUTH_SECRET=${DESKTOP_SECRET:?set by install.sh}
GH_CONFIG_DIR=/opt/data/home/.config/gh
GIT_CONFIG_GLOBAL=/opt/data/home/.gitconfig
API_SERVER_ENABLED=true
API_SERVER_HOST=127.0.0.1
API_SERVER_PORT=8642
API_SERVER_KEY=${API_SERVER_KEY:?set by install.sh}
PGHOST=127.0.0.1
PGPORT=${POSTGRES_PORT:-5432}
PGUSER=$POSTGRES_USER
PGPASSWORD=${POSTGRES_PASSWORD:?set by install.sh}
PGDATABASE=$POSTGRES_DB
DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@127.0.0.1:${POSTGRES_PORT:-5432}/$POSTGRES_DB
OBSIDIAN_VAULT_PATH=$HERMES_WORKSPACE_DIR/$OBSIDIAN_VAULT_DIR
WORKSPACE_DIR=$HERMES_WORKSPACE_DIR
EOF
  chown "root:$HERMES_GID" "$tmp"; chmod 640 "$tmp"; mv -f "$tmp" "$AGENT_ENV"
}

write_provenance() {
  local sha="$1" version
  version="$(sed -n 's/^version = "\(.*\)"/\1/p' "$HERMES_RELEASES/${sha:0:12}/pyproject.toml" | head -n1)"
  printf '{"deployment_kind":"image","image":"host:%s","manager":"command-center","revision":"%s","schema":1,"version":"%s"}\n' \
    "$HERMES_RELEASES" "$sha" "${version:-unknown}" > "$PROVENANCE.tmp"
  chmod 444 "$PROVENANCE.tmp"; mv -f "$PROVENANCE.tmp" "$PROVENANCE"
}

# hermes-gateway.service = what Hermes itself generates for a system unit (so `hermes gateway …`
# sees it as current), our settings in a drop-in (EnvironmentFile wins over its Environment=).
write_units() {
  local mem="${AGENT_MEM_LIMIT^^}"
  [ -e "$HERMES_CURRENT/.release" ] || die "no active release: sudo $0 build && sudo $0 activate <sha12>"
  env -i HOME=/root PATH="$(agent_path)" HERMES_HOME=/opt/data "$HERMES_CURRENT/.venv/bin/python" -c \
    'import sys; from hermes_cli.gateway_service_unit import generate_systemd_unit; sys.stdout.write(generate_systemd_unit(system=True, run_as_user=sys.argv[1]))' \
    "$OP_USER" > /etc/systemd/system/.hermes-gateway.service.tmp
  mv -f /etc/systemd/system/.hermes-gateway.service.tmp /etc/systemd/system/hermes-gateway.service
  install -d "$GATEWAY_DROPIN_DIR"
  sed -e "s|@CURRENT@|$HERMES_CURRENT|g" -e "s|@ENV@|$AGENT_ENV|g" -e "s|@MEM@|$mem|g" -e "s|@CPUS@|$((AGENT_CPUS * 100))%|g" \
    "$STACK_DIR/hermes/gateway-dropin.conf" > "$GATEWAY_DROPIN_DIR/10-command-center.conf"
  sed -e "s|@USER@|$OP_USER|g" -e "s|@CURRENT@|$HERMES_CURRENT|g" -e "s|@ENV@|$AGENT_ENV|g" \
    -e "s|@BIND@|${DESKTOP_BIND:-127.0.0.1}|g" -e "s|@PORT@|$DESKTOP_PORT|g" \
    "$STACK_DIR/hermes/hermes-dashboard.service" > "$DASHBOARD_UNIT"
  systemctl daemon-reload
  systemctl enable hermes-gateway.service hermes-dashboard.service >/dev/null 2>&1
}

# Traefik (container) → dashboard (host). File provider: the docker provider only sees containers.
write_route() {
  install -d -m 755 "$(dirname "$TRAEFIK_ROUTE")"
  cat > "$TRAEFIK_ROUTE.tmp" <<EOF
# Generated by hermes-host.sh units — https://$HERMES_HOST → the dashboard on the host.
http:
  routers:
    hermes:
      rule: Host(\`$HERMES_HOST\`)
      entryPoints: [websecure]
      tls:
        certResolver: cloudflare
      service: hermes
  services:
    hermes:
      loadBalancer:
        servers:
          - url: "http://${DESKTOP_BIND:-127.0.0.1}:$DESKTOP_PORT"
EOF
  chmod 644 "$TRAEFIK_ROUTE.tmp"; mv -f "$TRAEFIK_ROUTE.tmp" "$TRAEFIK_ROUTE"
}

# Traefik's packets come from the proxy bridge, not tailscale0: ufw must let them reach the
# dashboard port (harden.sh re-adds the same rule after its ufw reset).
allow_proxy_to_dashboard() {
  command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q '^Status: active' || return 0
  ufw allow proto tcp from "${PROXY_SUBNET:-172.20.0.0/16}" to any port "$DESKTOP_PORT" comment 'traefik → hermes dashboard (host)' >/dev/null
}

# The host-action approval gate (hermes/host-guard.py, option B): root-owned copy, consent for the
# gateway (non-TTY: exact command in Hermes' hook allowlist), and the hooks.pre_tool_call entry.
GUARD=/etc/hermes/host-guard.py
install_guard() {
  local hooks
  install -d -m 755 /etc/hermes
  install -m 755 -o root -g root "$STACK_DIR/hermes/host-guard.py" "$GUARD.tmp"
  "$GUARD.tmp" --self-test >/dev/null || { rm -f "$GUARD.tmp"; die "host-guard.py fails its self-test"; }
  mv -f "$GUARD.tmp" "$GUARD"
  runuser -u "$OP_USER" -- python3 -c '
import json, os, sys
path, cmd = sys.argv[1], sys.argv[2]
try:
    with open(path, encoding="utf-8") as f: data = json.load(f)
except FileNotFoundError: data = {}
approvals = data.setdefault("approvals", [])
if not any(a.get("event") == "pre_tool_call" and a.get("command") == cmd for a in approvals):
    approvals.append({"event": "pre_tool_call", "command": cmd})
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f: json.dump(data, f, indent=2); f.write("\n")
    os.chmod(tmp, 0o600); os.replace(tmp, path)
' "$HERMES_DATA_DIR/shell-hooks-allowlist.json" "$GUARD"
  hooks="$(agent_run python3 -c '
import json, sys, yaml
cmd = sys.argv[1]
with open("/opt/data/config.yaml", encoding="utf-8") as f: cfg = yaml.safe_load(f) or {}
entries = list(((cfg.get("hooks") or {}).get("pre_tool_call")) or [])
if not any(isinstance(e, dict) and e.get("command") == cmd for e in entries):
    entries.append({"matcher": "terminal|execute_code|write_file|patch", "command": cmd, "timeout": 10, "fail_closed": True})
    print(json.dumps(entries))
' "$GUARD")" || die "cannot read /opt/data/config.yaml"
  [ -z "$hooks" ] || agent_run hermes config set hooks.pre_tool_call "$hooks" >/dev/null
}

do_units() {
  no_symlink "$HERMES_DATA_DIR"
  if [ -L /opt/data ] || [ ! -e /opt/data ]; then ln -sfn "$HERMES_DATA_DIR" /opt/data
  else die "/opt/data exists and is not a symlink — expected a link to $HERMES_DATA_DIR"; fi
  write_agent_env
  write_units
  write_route
  allow_proxy_to_dashboard
  install_guard
  info "units, $AGENT_ENV, Traefik route, ufw rule and host-action guard written"
}

# ── activate / services ──────────────────────────────────────────────────
# activate <short> — current → <short>, previous → the old current; other complete releases pruned.
activate() {
  local short="$1" cur d
  [ -n "$(release_sha "$short")" ] || die "no complete release $short in $HERMES_RELEASES"
  cur="$(current_release)"
  if [ "$cur" != "$short" ]; then
    [ -z "$cur" ] || ln -sfn "$HERMES_RELEASES/$cur" "$HERMES_RELEASES/previous"
    ln -sfn "$HERMES_RELEASES/$short" "$HERMES_CURRENT.tmp" && mv -Tf "$HERMES_CURRENT.tmp" "$HERMES_CURRENT"
  fi
  ln -sfn "$STACK_DIR/bin/hermes" /usr/local/bin/hermes
  write_provenance "$(release_sha "$short")"
  for d in "$HERMES_RELEASES"/*/; do
    d="$(basename "$d")"
    case "$d" in "$short"|"$cur"|previous) ;; *) [ ! -e "$HERMES_RELEASES/$d/.release" ] || rm -rf "${HERMES_RELEASES:?}/$d" ;; esac
  done
  info "Hermes release: ${cur:-none} → $short"
}

services_restart() {
  systemctl restart hermes-gateway.service hermes-dashboard.service
  agent_wait_healthy 180
}

do_rollback() {
  local prev
  prev="$(basename "$(readlink -f "$HERMES_RELEASES/previous" 2>/dev/null || echo)")"
  [ -n "$prev" ] && [ -n "$(release_sha "$prev")" ] || die "no previous release kept"
  activate "$prev"
  do_units
  services_restart || warn "hermes not healthy after the rollback: journalctl -u hermes-gateway -u hermes-dashboard"
}

do_status() {
  local cur prev
  cur="$(current_release)"; prev="$(basename "$(readlink -f "$HERMES_RELEASES/previous" 2>/dev/null || echo)")"
  printf '  %-10s %s\n' release "${cur:-none}  $(release_sha "$cur")" previous "${prev:-none}"
  printf '  %-10s %s\n' gateway "$(systemctl is-active hermes-gateway 2>/dev/null || true)" dashboard "$(systemctl is-active hermes-dashboard 2>/dev/null || true)"
  if agent_healthy; then printf '  %-10s %s\n' health "ok (gateway /health + dashboard /api/status)"
  else printf '  %-10s %s\n' health "NOT OK"; fi
}

# A build (uv, npm, vite) takes GBs of RAM: run it in its own transient unit, never in the caller's
# cgroup — from a herdr pane (herdr.service MemoryMax) the OOM killer would take the terminal too.
build_in_own_unit() {
  [ "${HERMES_BUILD_UNIT:-}" = 1 ] && return 0
  command -v systemd-run >/dev/null 2>&1 || return 0
  exec systemd-run --quiet --pipe --wait --collect --unit="hermes-build-$$" \
    -p MemoryMax="${HERMES_BUILD_MEM:-8G}" -p MemorySwapMax=0 -E HERMES_BUILD_UNIT=1 \
    "$(readlink -f "$0")" build "$@"
}

cmd="${1:-}"; [ $# -gt 0 ] && shift
case "$cmd" in
  build)    build_in_own_unit "$@"; do_build "${1:-}"; echo "$BUILT_SHORT" ;;
  # A new release may ship a new unit template: regenerate it before the restart.
  activate) [ -n "${1:-}" ] || die "usage: $0 activate <sha12>"; activate "$1"; do_units; services_restart ;;
  resolve)  resolve_ref "${1:-$HERMES_REF}" ;;
  current)  current_release ;;
  rollback) do_rollback ;;
  units)    do_units ;;
  start)    systemctl start hermes-gateway.service hermes-dashboard.service; agent_wait_healthy 180 ;;
  stop)     systemctl stop hermes-dashboard.service hermes-gateway.service ;;
  restart)  services_restart ;;
  status)   do_status ;;
  releases) ls -1 "$HERMES_RELEASES" 2>/dev/null || true; echo "current: $(current_release)" ;;
  probe)    smoke_test "$HERMES_CURRENT" ;;
  healthy)  agent_healthy ;;
  -h|--help|help|"") sed -n '2,12p' "$0" ;;
  *) die "usage: $0 {build [ref]|activate <sha12>|rollback|units|start|stop|restart|status|releases|probe|healthy|resolve [ref]|current}" ;;
esac
